devs:
  children:
    home_dev:
      hosts:
        home-server:
          physical_location: home
          ansi_worker: ans-leo
          dev_user: leogray
    office_dev:
      hosts:
        leo-tower:
          physical_location: office
          ansi_worker: ans-leo
          dev_user: leogray

  vars:
    target_user: leogray