--- 
- name: Install dev tools and packages (for non GUI tools)
  hosts: all 

# This requires {{ dev_user }} variable exists for dev hosts.

  tasks:

    # ==> For installing micro 
    - name: Get the dev user home dir
      become: yes 
      become_user: "{{ dev_user }}"
      shell: 
        cmd: "echo $HOME"
      changed_when: false
      register: dev_home

    - name: Print dev_home variable
      debug:
        var: dev_home.stdout

    - name: Check if micro is installed
      stat:
        path: "/usr/bin/micro"
      register: micro_file

    - name: install micro
      become: true
      become_user: root
      shell:
        chdir: "/usr/bin"
        cmd: "curl https://getmic.ro | bash"
      when: not micro_file.stat.exists
      notify: micro just installed
    
    - name: Force run micro install's handlers
      meta: flush_handlers
    # For installing micro <==


    # Trans is great for checking english
    - name: Install trans
      become: true
      become_user: root
      apt: 
        name: translate-shell
      notify: translate-shell just installed
      # For now, the translate-shell config is copied together with the entire config folder

      # TODO, specially for fd-find, this post step is needed ln -s $(which fdfind) ~/.local/bin/fd
      # TODO add ripgrep
    - name: Install good tools for shell usage fzf , tldr , bat, fd-find, aptitude
      become: true
      become_user: root 
      apt:
        name: [fzf , tldr , bat  , fd-find , aptitude]

  handlers:

  # Happens only when micro is installed
    - name: install micro clipboard tool
      become: true 
      apt: 
        name: [xclip , xsel]
      listen: micro just installed

    - name: Copy micro config files
      become: yes 
      become_user: "{{ dev_user }}"
      copy:
        src: user-configs/micro
        dest: "{{ dev_home.stdout }}/.config"
        backup: yes
        force: no
      listen: micro just installed

  # Happens only when micro is installed

  # Happens only when translate-shell is installed
    
    - name: Copy translate shell config 
      become: yes 
      become_user: "{{ dev_user }}"
      copy:
        src: user-configs/translate-shell
        dest: "{{ dev_home.stdout }}/.config"
        backup: yes
        force: no
      listen: translate-shell just installed


    
    
