--- 
- name: Install dev tools and packages (for non GUI tools)
  hosts: all 

# This requires {{ dev_user }} variable exists for dev hosts.

  tasks:

    # These two steps are needed to place config file for micro and trans
    - name: Get the dev user home dir
      become: yes 
      become_user: "{{ dev_user }}"
      shell: 
        cmd: "echo $HOME"
      changed_when: false
      register: dev_home

    - name: Print dev_home variable
      debug:
        var: dev_home.stdout

    
    # ==> For installing micro 
    
    # This bit for Arch 
    - name: Install micro
      become: yes
      become_user: root
      package: 
        name: micro
      when: ansible_facts['os_family'] == "Archlinux"


    - name: Check if micro is installed
      stat:
        path: "/usr/bin/micro"
      register: micro_file

    # This bit for ubuntu 
    - name: install micro
      become: true
      become_user: root
      shell:
        chdir: "/usr/bin"
        cmd: "curl https://getmic.ro | bash"
      when: (not micro_file.stat.exists) and ansible_facts['os_family'] != "Archlinux" # I just assume everything else is just ubuntu relatives

    - name: Copy micro config files
      become: yes 
      become_user: "{{ dev_user }}"
      copy:
        src: user-configs/micro
        dest: "{{ dev_home.stdout }}/.config"
        backup: yes
        force: no
    
    # For installing micro <==

    - name: install clipboard tool
      become: true 
      package: 
        name: [xclip , xsel]

      # TODO add ripgrep
    - name: Install good tools for shell usage
      become: true
      become_user: root
      package:
        name: [fzf , tldr , bat , ripgrep]

      
      # TODO, specially for ubuntu, fd-find need to be put onto bin ln -s $(which fdfind) ~/.local/bin/fd
    - name: Install fd-find in arch
      become: true 
      become_user: root
      package: 
        name: fd
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Install ubuntu specific packages 
      become: true 
      become_user: root
      package: 
        name: [fd-find , aptitude]
      when: ansible_facts['os_family'] == "Ubuntu"


    - name: Install mcfly
      become: true
      become_user: root
      shell:
        cmd: "curl -LSfs https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh | sh -s -- --git cantino/mcfly --force"
      
    # Trans is great for checking english
    - name: Install trans
      become: true
      become_user: root
      package: 
        name: translate-shell
      notify: translate-shell just installed
      # For now, the translate-shell config is copied together with the entire config folder

    - name: Install pssh
      become: true
      become_user: root
      package: 
        name: pssh

  handlers:

  # Happens only when translate-shell is installed
    
    - name: Copy translate shell config 
      become: yes 
      become_user: "{{ dev_user }}"
      copy:
        src: user-configs/translate-shell
        dest: "{{ dev_home.stdout }}/.config"
        backup: yes
        force: no
      listen: translate-shell just installed


    
    
