---

- name: Install some basic packets. (git curl etc)
  hosts: all
  become: true
  become_method: sudo

  tasks:

    - name: install git, curl, tree, htop, most
      package:
        name: [git , curl , tree , acl , htop , most]
        state: latest

