---

- name: Install some basic packets. (git curl etc)
  hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 172800

    - name: install git, curl, tree, htop
      apt:
        name: [git , curl , tree , acl , htop]
        state: latest

