--- 
- name: Initial User setup on dev machine. Ensure 2 user exist, and both are no password sudo 
  hosts: all
  become: yes

  tasks: 
    - name: Make sure dev user is created
      user:
        name: "{{ dev_user }}"

        # group: "{{ dev_user }}"
        append: yes
        groups: "sudo"
        create_home: yes

    - name: Ensure sudoer file is set to also load sudoer.d
      lineinfile:
        path: /etc/sudoers
        state: present
        line: "#includedir /etc/sudoers.d"
        validate: "/usr/sbin/visudo -cf %s"

    - name: Add dev user to sudo
      lineinfile:
        path: /etc/sudoers.d/{{ dev_user }}
        line: "{{ dev_user }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0640
        create: yes
        validate: 'visudo -cf %s'

    
