--- 
- name: Initial User setup on dev machine. Ensure 2 user exist, and both are no password sudo 
  hosts: all
  become: yes

  tasks: 
    - name: Ensure sudoer file is set to also load sudoer.d
      lineinfile:
        path: /etc/sudoers
        state: present
        line: "#includedir /etc/sudoers.d"
        validate: "/usr/sbin/visudo -cf %s"

    - name: Add dev user to sudo
      lineinfile:
        path: /etc/sudoers.d/{{ dev_user }}
        line: "{{ dev_user }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0640
        create: yes
        # owner: "{{ dev_user }}"
        validate: 'visudo -cf %s'

    - name: Make sure ansible worker account is established. 
      user:
        name: "{{ ansi_worker }}"
        group: "{{ dev_user }}"
        groups: "sudo"
        create_home: yes
        home: /home/ansible-junk-yard
    
    - name: Add user ansible worker to sudo
      lineinfile:
        path: /etc/sudoers.d/ansi_worker
        line: "{{ ansi_worker }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0640
        create: yes
        # owner: "{{ ansi_worker }}"
        validate: 'visudo -cf %s'