version: 3
profiles:
  - type: ssh
    name: spring-bok
    icon: fas fa-desktop
    options:
      host: 10.164.2.77
      user: runneradm
      algorithms: {}
      keepaliveInterval: 1000
      keepaliveCountMax: 50
      forwardedPorts:
        - type: Local
          host: 127.0.0.1
          port: 4444
          targetAddress: 127.0.0.1
          targetPort: 4444
        - type: Local
          host: 127.0.0.1
          port: 8888
          targetAddress: 127.0.0.1
          targetPort: 80
      privateKeys:
        - file:///home/leogray/.ssh/id_rsa
    weight: -1
    id: ssh:custom:spring-bok:27838f9b-d6f9-4606-8d01-1ac36a73da10
  - type: ssh
    name: aws-box
    icon: fas fa-desktop
    options:
      host: 18.212.164.60
      user: leogray
      algorithms: {}
      privateKeys:
        - file:///home/leogray/.ssh/awskey.key
      keepaliveInterval: 1000
      keepaliveCountMax: 50
      forwardedPorts:
        - type: Local
          host: 127.0.0.1
          port: 4444
          targetAddress: 127.0.0.1
          targetPort: 4444
        - type: Local
          host: 127.0.0.1
          port: 3333
          targetAddress: 127.0.0.1
          targetPort: 3000
    weight: -1
    id: ssh:custom:aws-box:7d1611a1-6a82-4340-8ba8-632567cffd3c
hotkeys:
  toggle-window: []
  copy:
    - Ctrl-Shift-C
  paste:
    - - Ctrl-Shift-V
  home:
    - Home
  end:
    - End
  previous-word:
    - Ctrl-Left
  next-word:
    - Ctrl-Right
  delete-previous-word:
    - Ctrl-Backspace
  delete-next-word:
    - Ctrl-Delete
  clear: []
  zoom-in:
    - - Ctrl-Shift-=
  zoom-out:
    - - Ctrl-Shift--
  reset-zoom:
    - Ctrl-0
  ctrl-c:
    - Ctrl-C
  copy-current-path: []
  search:
    - Ctrl-Shift-F
  pane-focus-all:
    - Ctrl-Shift-I
  restart-telnet-session: []
  settings:
    - Ctrl-,
  serial: []
  restart-serial-session: []
  new-window:
    - Ctrl-Shift-N
  new-tab:
    - Ctrl-Shift-T
  profile-selector:
    - Ctrl-Shift-T
  toggle-fullscreen:
    - F11
  rename-tab:
    - Ctrl-Shift-R
  close-tab:
    - Ctrl-Shift-W
  reopen-tab:
    - Ctrl-Shift-T
  toggle-last-tab: []
  next-tab:
    - - Ctrl-PageDown
  previous-tab:
    - - Ctrl-PageUp
  move-tab-left: []
  move-tab-right: []
  rearrange-panes:
    - Ctrl-Shift
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - - Ctrl-Shift-\
  split-bottom:
    - - Ctrl-Shift--
  split-left: []
  split-top: []
  pane-maximize:
    - - Ctrl-Shift-X
  pane-nav-up:
    - Ctrl-Alt-Up
  pane-nav-down:
    - Ctrl-Alt-Down
  pane-nav-left:
    - Ctrl-Alt-Left
  pane-nav-right:
    - Ctrl-Alt-Right
  pane-nav-previous:
    - - Ctrl-Shift-Tab
  pane-nav-next:
    - - Ctrl-Tab
  switch-profile:
    - Ctrl-Alt-T
  close-pane: []
  profile: {}
  profile-selectors: {}
  select-all:
    - Ctrl-Shift-A
  restart-ssh-session: []
  launch-winscp: []
terminal:
  searchOptions: {}
  colorScheme:
    name: Molokai
    foreground: '#bbbbbb'
    background: '#121212'
    cursor: '#bbbbbb'
    colors:
      - '#121212'
      - '#fa2573'
      - '#98e123'
      - '#dfd460'
      - '#1080d0'
      - '#8700ff'
      - '#43a8d0'
      - '#bbbbbb'
      - '#555555'
      - '#f6669d'
      - '#b1e05f'
      - '#fff26d'
      - '#00afff'
      - '#af87ff'
      - '#51ceff'
      - '#ffffff'
  customColorSchemes: []
  cursor: beam
  background: colorScheme
  font: DejaVu Sans Mono
  fontSize: 16
  autoOpen: true
  pasteOnMiddleClick: false
ssh:
  warnOnClose: true
configSync:
  parts: {}
appearance:
  opacity: 0.86
  tabsLocation: bottom
pluginBlacklist: []
profileDefaults: {}
electronFlags:
  - - force_discrete_gpu
    - '0'
